apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:7.2.0
          command: ["filebeat", "-e", "-strict.perms=false"]
          volumeMounts:
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml
              readOnly: true
            - name: docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: docker-socket
              mountPath: /var/run/docker.sock
              readOnly: true
            - name: filebeat-data
              mountPath: /usr/share/filebeat/data
              readOnly: false
      volumes:
        - name: filebeat-config
          configMap:
            name: filebeat-config
        - name: docker-containers
          hostPath:
            path: /var/lib/docker/containers
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: filebeat-data
          emptyDir: {}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
        - type: docker
          labels.dedot: true
          templates:
            - condition:
                contains:
                  container.labels.collect_logs_with_filebeat: "true"
              config:
                - type: container
                  format: docker
                  paths:
                    - "/var/lib/docker/containers/${data.docker.container.id}/*.log"
                  processors:
                    - decode_json_fields:
                        when.equals:
                          docker.container.labels.decode_log_event_to_json_object: "true"
                        fields: ["message"]
                        target: ""
                        overwrite_keys: true

    output.logstash:
      hosts: ["logstash:5044"]

    logging.metrics.enabled: false

---
apiVersion: v1
kind: Service
metadata:
  name: filebeat
  labels:
    app: filebeat
spec:
  ports:
    - port: 5044
      protocol: TCP
      targetPort: 5044
  selector:
    app: filebeat
