version: '4'
services:
  user_service_db:
    image: postgres:latest
    container_name: user
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_service
    ports:
      - "5434:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data