apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  labels:
    app: email-service
    collect_logs_with_filebeat: "true"
    decode_log_event_to_json_object: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
        collect_logs_with_filebeat: "true"
        decode_log_event_to_json_object: "true"
    spec:
      containers:
        - name: email-service
          image: benabbouosama/spring-boot-microservices-e-commerce-project:email-service-latest
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084
  selector:
    app: email-service
