version: '4'
services:
  inventory_service_db:
    image: postgres:latest
    container_name: inventory
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_service
    ports:
      - "5433:5432"
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
